- .gitignore
- pom.xml
- src/main/java/fi/metatavu/famifarm/persistence/dao/TeamDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/Team.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/TeamsTranslator.java
- src/main/java/fi/metatavu/famifarm/teams/TeamsController.java
- src/main/java/teams/TeamsController.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/TeamTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/auth/AbstractTestBuilderAuthentication.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/TeamTestBuilderResource.java
- travis.sh
> Feature 3 teams

- .gitignore
- pom.xml
- src/main/java/fi/metatavu/famifarm/persistence/dao/SeedBatchDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/SeedBatch.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/SeedBatchTranslator.java
- src/main/java/fi/metatavu/famifarm/seedbatches/SeedBatchesController.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/SeedBatchTestIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/auth/AbstractTestBuilderAuthentication.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/SeedBatchTestBuilderResource.java
> Added seed batches

- pom.xml
- src/main/java/fi/metatavu/famifarm/batches/BatchController.java
- src/main/java/fi/metatavu/famifarm/packagesizes/PackageSizeController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/BatchDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/PackageSizeDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/ProductDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/Batch.java
- src/main/java/fi/metatavu/famifarm/persistence/model/PackageSize.java
- src/main/java/fi/metatavu/famifarm/persistence/model/Product.java
- src/main/java/fi/metatavu/famifarm/products/ProductController.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/BatchTranslator.java
- src/main/java/fi/metatavu/famifarm/rest/translate/PackageSizeTranslator.java
- src/main/java/fi/metatavu/famifarm/rest/translate/ProductsTranslator.java
- src/main/java/fi/metatavu/famifarm/rest/translate/SeedBatchTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/BatchTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/PackageSizeTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/ProductTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/auth/AbstractTestBuilderAuthentication.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/BatchTestBuilderResource.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/PackageSizeTestBuilderResource.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/ProductTestBuilderResource.java
> Feature 9 batches

- pom.xml
> Bumped Wildfly version

- src/main/java/fi/metatavu/famifarm/persistence/dao/BatchDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/ProductionLineDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/ProductionLine.java
- src/main/java/fi/metatavu/famifarm/productionlines/ProductionLineController.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/ProductionLineTranslator.java
- src/main/java/fi/metatavu/famifarm/rest/translate/ProductsTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/BatchTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/ProductionLineTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/auth/AbstractTestBuilderAuthentication.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/BatchTestBuilderResource.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/PackageSizeTestBuilderResource.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/ProductionLineTestBuilderResource.java
> Feature 10 production lines

- .travis.yml
- pom.xml
- scripts/setup-db-mysql.sql
- scripts/setup-db.sql
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- travis.sh
> use mariadb

- .gitignore
- pom.xml
- run-test.sh
- src/main/java/fi/metatavu/famifarm/events/EventController.java
- src/main/java/fi/metatavu/famifarm/events/SowingEventController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/EventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/SowingEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/Event.java
- src/main/java/fi/metatavu/famifarm/persistence/model/SowingEvent.java
- src/main/java/fi/metatavu/famifarm/rest/AbstractApi.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/AbstractEventTranslator.java
- src/main/java/fi/metatavu/famifarm/rest/translate/SowingEventTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/SeedBatchTestIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/auth/AbstractTestBuilderAuthentication.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/EventTestBuilderResource.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/SeedBatchTestBuilderResource.java
> Sowing events

- src/main/java/fi/metatavu/famifarm/performedcultivationactions/PerformedCultivationActionsController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/PerformedCultivationActionDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/PerformedCultivationAction.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/PerformedCultivationActionTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/PerformedCultivationActionTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/auth/AbstractTestBuilderAuthentication.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/PerformedCultivationActionTestBuilderResource.java
> Added performed cultivation action

- src/main/java/fi/metatavu/famifarm/events/TableSpreadEventController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/TableSpreadEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/TableSpreadEvent.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/TableSpreadEventTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/EventTestBuilderResource.java
> Feature 26 table spread event

- src/main/java/fi/metatavu/famifarm/events/CultivationObservationEventController.java
- src/main/java/fi/metatavu/famifarm/events/EventController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/CultivationObservationEventActionDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/CultivationObservationEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/CultivationObservationEvent.java
- src/main/java/fi/metatavu/famifarm/persistence/model/CultivationObservationEventAction.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/CultivationObservationEventTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/EventTestBuilderResource.java
> Added support for cultivation observation events

- src/main/java/fi/metatavu/famifarm/events/HarvestEventController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/HarvestEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/HarvestEvent.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/HarvestEventTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/EventTestBuilderResource.java
> Added support for harvest events

- src/main/java/fi/metatavu/famifarm/events/PlantingEventController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/PlantingEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/PlantingEvent.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/PlantingEventTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/EventTestBuilderResource.java
> Added support for planting events

- src/main/java/fi/metatavu/famifarm/events/PackingEventController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/PackingEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/PackingEvent.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/PackingEventTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/EventTestBuilderResource.java
> Added support for packing events

- pom.xml
- src/main/java/fi/metatavu/famifarm/events/WastageEventController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/WastageEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/WastageEvent.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/WastageEventTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/EventTestBuilderResource.java
> Added support for wastage events

- pom.xml
- src/main/java/fi/metatavu/famifarm/events/EventController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/EventDAO.java
- src/main/java/fi/metatavu/famifarm/reporting/xlsx/XlsxExampleReport.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/BatchTranslator.java
- src/test/java/fi/metatavu/famifarm/test/functional/AbstractFunctionalTest.java
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/ReportTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/EventTestBuilderResource.java
> Added batchId filter to events endpoint

- pom.xml
- src/main/java/fi/metatavu/famifarm/batches/BatchController.java
- src/main/java/fi/metatavu/famifarm/events/CultivationObservationEventController.java
- src/main/java/fi/metatavu/famifarm/events/EventController.java
- src/main/java/fi/metatavu/famifarm/events/HarvestEventController.java
- src/main/java/fi/metatavu/famifarm/events/PackingEventController.java
- src/main/java/fi/metatavu/famifarm/events/PlantingEventController.java
- src/main/java/fi/metatavu/famifarm/events/SowingEventController.java
- src/main/java/fi/metatavu/famifarm/events/TableSpreadEventController.java
- src/main/java/fi/metatavu/famifarm/events/WastageEventController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/AbstractEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/BatchDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/CultivationObservationEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/EventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/HarvestEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/PackingEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/PlantingEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/SowingEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/TableSpreadEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/WastageEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/Batch.java
- src/main/java/fi/metatavu/famifarm/persistence/model/Event.java
- src/main/java/fi/metatavu/famifarm/rest/BatchListStatus.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/BatchTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/BatchTestBuilderResource.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/EventTestBuilderResource.java
> Added support for filtering batches by status

- pom.xml
- src/main/java/fi/metatavu/famifarm/batches/BatchController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/BatchDAO.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/test/java/fi/metatavu/famifarm/test/functional/BatchTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/BatchTestBuilderResource.java
> Added created filter for batches

- pom.xml
- src/main/java/fi/metatavu/famifarm/events/PlantingEventController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/PlantingEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/PlantingEvent.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/PlantingEventTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/BatchTestBuilderResource.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/EventTestBuilderResource.java
> Renamed planting gutter number -> gutter size

- pom.xml
- src/main/java/fi/metatavu/famifarm/events/PlantingEventController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/PlantingEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/PlantingEvent.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/PlantingEventTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/EventTestBuilderResource.java
> Hotfix 56 tray cell

- pom.xml
- src/main/java/fi/metatavu/famifarm/drafts/DraftController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/BatchDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/DraftDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/Draft.java
- src/main/java/fi/metatavu/famifarm/rest/AbstractApi.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/BatchTranslator.java
- src/main/java/fi/metatavu/famifarm/rest/translate/DraftTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/BatchTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/DraftTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/auth/AbstractTestBuilderAuthentication.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/DraftTestBuilderResource.java
> Added support for drafts

- pom.xml
- src/main/java/fi/metatavu/famifarm/events/SowingEventController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/SowingEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/SowingEvent.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/SowingEventTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/AbstractFunctionalTest.java
- src/test/java/fi/metatavu/famifarm/test/functional/BatchTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/EventTestBuilderResource.java
> Hotfix 60 remove sowing gutter

- pom.xml
- src/main/java/fi/metatavu/famifarm/persistence/dao/ProductionLineDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/ProductionLine.java
- src/main/java/fi/metatavu/famifarm/productionlines/ProductionLineController.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/ProductionLineTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/AbstractFunctionalTest.java
- src/test/java/fi/metatavu/famifarm/test/functional/BatchTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/ProductionLineTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/ProductionLineTestBuilderResource.java
> Added default team into production lines

- pom.xml
- src/main/java/fi/metatavu/famifarm/batches/BatchController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/BatchDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/WastageEvent.java
- src/main/java/fi/metatavu/famifarm/reporting/xlsx/XlsxWastageReport.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/WastageEventTranslator.java
- src/test/java/fi/metatavu/famifarm/test/functional/BatchTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/BatchTestBuilderResource.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/EventTestBuilderResource.java
> Feature 71 batch list product filter

- src/main/java/fi/metatavu/famifarm/reporting/ReportController.java
- src/main/java/fi/metatavu/famifarm/reporting/ReportType.java
- src/main/java/fi/metatavu/famifarm/reporting/xlsx/XlsxGrowthTimeReport.java
- src/test/java/fi/metatavu/famifarm/test/functional/AbstractFunctionalTest.java
- src/test/java/fi/metatavu/famifarm/test/functional/ReportTestsIT.java
> Feature 70 growth time reports

- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
> Fixed issue #86

- src/main/java/fi/metatavu/famifarm/reporting/xlsx/XlsxGrowthTimeReport.java
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
> Fixed issue #95

- pom.xml
- src/main/java/fi/metatavu/famifarm/events/HarvestEventController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/HarvestEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/HarvestEvent.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/HarvestEventTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/AbstractFunctionalTest.java
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/EventTestBuilderResource.java
> Added team to harvest event

- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
> Fixed issue #102

- pom.xml
- src/main/java/fi/metatavu/famifarm/batches/BatchController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/BatchDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/Batch.java
- src/main/java/fi/metatavu/famifarm/reporting/xlsx/XlsxEventCountReport.java
- src/main/java/fi/metatavu/famifarm/reporting/xlsx/XlsxGrowthTimeReport.java
- src/main/java/fi/metatavu/famifarm/reporting/xlsx/XlsxPlantingYieldReport.java
- src/main/java/fi/metatavu/famifarm/reporting/xlsx/XlsxWastageReport.java
- src/main/java/fi/metatavu/famifarm/reporting/xlsx/XlsxYieldReport.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/BatchTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/BatchTestBuilderResource.java
> Added phase to batch

- src/main/java/fi/metatavu/famifarm/reporting/xlsx/XlsxWastageReport.java
> Added null checks to wastage report

- src/main/java/fi/metatavu/famifarm/batches/BatchController.java
- src/test/java/fi/metatavu/famifarm/test/functional/AbstractFunctionalTest.java
- src/test/java/fi/metatavu/famifarm/test/functional/BatchTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
> Treat amount in sowing event as tray count instead of number of units

- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/test/java/fi/metatavu/famifarm/test/functional/BatchTestsIT.java
> Added permission for users with worker role to create batches

- src/main/java/fi/metatavu/famifarm/batches/BatchController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/BatchDAO.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
> When creating or updating sowing events, refresh batch creation date

- pom.xml
- src/main/java/fi/metatavu/famifarm/events/SowingEventController.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/BatchTranslator.java
- src/main/java/fi/metatavu/famifarm/rest/translate/TableSpreadEventTranslator.java
- src/test/java/fi/metatavu/famifarm/test/functional/AbstractFunctionalTest.java
- src/test/java/fi/metatavu/famifarm/test/functional/BatchTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/EventTestBuilderResource.java
> Added sowingLineNumbers field into batch REST entity

- pom.xml
- src/main/java/fi/metatavu/famifarm/events/SowingEventController.java
- src/main/java/fi/metatavu/famifarm/events/TableSpreadEventController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/SowingEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/SowingEventSeedBatchDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/TableSpreadEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/SowingEvent.java
- src/main/java/fi/metatavu/famifarm/persistence/model/SowingEventSeedBatch.java
- src/main/java/fi/metatavu/famifarm/persistence/model/TableSpreadEvent.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/SowingEventTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/AbstractFunctionalTest.java
- src/test/java/fi/metatavu/famifarm/test/functional/BatchTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/EventTestBuilderResource.java
> Feature 130 sowing event seed batches

- src/main/java/fi/metatavu/famifarm/batches/BatchController.java
- src/main/java/fi/metatavu/famifarm/events/EventController.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
> Added support for batch deletion

- pom.xml
- src/main/java/fi/metatavu/famifarm/persistence/dao/SeedBatchDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/SeedBatch.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/SeedBatchTranslator.java
- src/main/java/fi/metatavu/famifarm/seedbatches/SeedBatchesController.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/SeedBatchTestIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/SeedBatchTestBuilderResource.java
> Feature 145 active passive seed batches

- pom.xml
- src/main/java/fi/metatavu/famifarm/printing/PrintingController.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/test/java/fi/metatavu/famifarm/test/functional/BatchTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/PrintingTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/ReportTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/auth/AbstractTestBuilderAuthentication.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/PrintingTestBuilderResource.java
> Feature 160 printing api

- src/main/java/fi/metatavu/famifarm/events/HarvestEventController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/HarvestEventDAO.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/PrintingTestsIT.java
> Hopefully fixed the bug

- pom.xml
- src/main/java/fi/metatavu/famifarm/campaigns/CampaignController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/CampaignDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/CampaignProductDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/Campaign.java
- src/main/java/fi/metatavu/famifarm/persistence/model/CampaignProduct.java
- src/main/java/fi/metatavu/famifarm/products/ProductController.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/CampaignTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/CampaignTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/auth/AbstractTestBuilderAuthentication.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/BatchTestBuilderResource.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/CampaignTestBuilderResource.java
> Feature 182 campaigns

- pom.xml
- src/main/java/fi/metatavu/famifarm/packing/PackingController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/PackingDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/Packing.java
- src/main/java/fi/metatavu/famifarm/printing/PrintingController.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/PackingTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/PackingTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/PrintingTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/ReportTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/PackingTestBuilderResource.java
> Added support for campaign packings

- src/main/java/fi/metatavu/famifarm/printing/PrintingController.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
> Allowing to print campaign packings

- src/main/java/fi/metatavu/famifarm/batches/BatchController.java
- src/main/java/fi/metatavu/famifarm/events/SowingEventController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/BatchDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/Batch.java
- src/main/java/fi/metatavu/famifarm/reporting/xlsx/XlsxGrowthTimeReport.java
- src/main/java/fi/metatavu/famifarm/reporting/xlsx/XlsxWastageReport.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/BatchTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/BatchTestBuilderResource.java
> Feature 185 remaining units errors

- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
> Changed timestamp to datetime(6) in database

- pom.xml
- src/main/java/fi/metatavu/famifarm/persistence/dao/ProductDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/Product.java
- src/main/java/fi/metatavu/famifarm/products/ProductController.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/ProductsTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/AbstractFunctionalTest.java
- src/test/java/fi/metatavu/famifarm/test/functional/BatchTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/CampaignTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/PackingTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/PrintingTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/ProductTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/ReportTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/ProductTestBuilderResource.java
> Added subcontractor products

- src/main/java/fi/metatavu/famifarm/packagesizes/PackageSizeController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/ProductDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/ProductPackageSizeDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/Product.java
- src/main/java/fi/metatavu/famifarm/persistence/model/ProductPackageSize.java
- src/main/java/fi/metatavu/famifarm/products/ProductController.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/ProductsTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/main/resources/swagger.yaml
- src/test/java/fi/metatavu/famifarm/test/functional/AbstractFunctionalTest.java
- src/test/java/fi/metatavu/famifarm/test/functional/CampaignTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/CutPackingTestIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/PackingTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/PrintingTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/ProductTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/ReportTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/ProductTestBuilderResource.java
Resolves https://github.com/Metatavu/famifarm-api/issues/218
> Feature 218 package sizes

- src/main/java/fi/metatavu/famifarm/events/EventController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/EventDAO.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/resources/swagger.yaml
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/EventTestBuilderResource.java
Resolves https://github.com/Metatavu/famifarm-api/issues/221
> added event type filter and test

- src/test/java/fi/metatavu/famifarm/test/functional/ReportTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/ReportTestBuilderResource.java
Resolves https://github.com/Metatavu/famifarm-api/issues/228
> fixed import

- src/main/java/fi/metatavu/famifarm/discards/StorageDiscardController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/StorageDiscardDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/StorageDiscard.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/StorageDiscardTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/main/resources/swagger.yaml
- src/test/java/fi/metatavu/famifarm/test/functional/StorageDiscardTestIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/auth/AbstractTestBuilderAuthentication.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/StorageDiscardTestBuilderResource.java
Resolves https://github.com/Metatavu/famifarm-api/issues/239
> added storage discard specs, database entity, functionality and tests

- src/main/java/fi/metatavu/famifarm/rest/interceptors/FacilityInterceptor.java
- src/main/resources/test-realm.json
- src/test/java/fi/metatavu/famifarm/test/functional/CampaignTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/CutPackingTestIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/DraftTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/PackageSizeTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/PerformedCultivationActionTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/PestTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/ProductTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/SeedTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/StorageDiscardTestIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/WastageReasonTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/TestBuilder.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/CampaignTestBuilderResource.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/CutPackingTestBuilderResource.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/EventTestBuilderResource.java
> Feature 262 restrict access to non authorized facility

- src/main/java/fi/metatavu/famifarm/rest/interceptors/FacilityInterceptor.java
- src/test/java/fi/metatavu/famifarm/test/functional/SystemTestIT.java
> Fix FacilityInterceptor to allow access to ping endpoint

- src/main/java/fi/metatavu/famifarm/events/EventController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/EventDAO.java
- src/main/java/fi/metatavu/famifarm/reporting/json/JsonWastageReport.java
- src/main/java/fi/metatavu/famifarm/reporting/xlsx/XlsxEventCountReport.java
- src/main/java/fi/metatavu/famifarm/reporting/xlsx/XlsxGrowthTimeReport.java
- src/main/java/fi/metatavu/famifarm/reporting/xlsx/XlsxPlantingYieldReport.java
- src/main/java/fi/metatavu/famifarm/reporting/xlsx/XlsxProductPhaseCountReport.java
- src/main/java/fi/metatavu/famifarm/reporting/xlsx/XlsxSeedlingTimeReport.java
- src/main/java/fi/metatavu/famifarm/reporting/xlsx/XlsxWastageReport.java
- src/main/java/fi/metatavu/famifarm/reporting/xlsx/XlsxYieldReport.java
- src/test/java/fi/metatavu/famifarm/test/functional/ReportTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/ReportTestBuilderResource.java
https://github.com/Metatavu/famifarm-api/issues/278
> added Facility filtering to reports generation of events

- src/main/java/fi/metatavu/famifarm/events/HarvestEventController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/HarvestBasketDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/HarvestEventDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/HarvestBasket.java
- src/main/java/fi/metatavu/famifarm/persistence/model/HarvestEvent.java
- src/main/java/fi/metatavu/famifarm/reporting/EventCountController.java
- src/main/java/fi/metatavu/famifarm/reporting/xlsx/XlsxlSummaryReport.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/HarvestEventTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/AbstractFunctionalTest.java
- src/test/java/fi/metatavu/famifarm/test/functional/EventTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/ReportTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/AbstractTestBuilderResource.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/EventTestBuilderResource.java
https://github.com/Metatavu/famifarm-api/issues/287
> Feature 287 harvested baskets

- src/main/java/fi/metatavu/famifarm/packings/PackingController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/AbstractDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/PackingBasketDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/PackingVerificationWeightingDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/PackingBasket.java
- src/main/java/fi/metatavu/famifarm/persistence/model/PackingVerificationWeighting.java
- src/main/java/fi/metatavu/famifarm/products/ProductController.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/PackingTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/PackingTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/PackingTestBuilderResource.java
https://github.com/Metatavu/famifarm-api/issues/292
> Feature 292 weightings baskets packing

- src/main/java/fi/metatavu/famifarm/packings/PackingController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/PackingDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/Packing.java
- src/main/java/fi/metatavu/famifarm/rest/translate/PackingTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/PackingTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/PackingTestBuilderResource.java
https://github.com/Metatavu/famifarm-api/issues/294
> Feature 294 packing dates additional info

- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/test/java/fi/metatavu/famifarm/test/functional/PackingTestsIT.java
https://github.com/Metatavu/famifarm-api/issues/297
> fix basket using the main product by default

- src/main/java/fi/metatavu/famifarm/packings/PackingController.java
- src/test/java/fi/metatavu/famifarm/test/functional/PackingTestsIT.java
https://github.com/Metatavu/famifarm-api/issues/300
> packing count

- src/main/java/fi/metatavu/famifarm/reporting/xlsx/listreports/XlsxHarvestListReport.java
- src/main/java/fi/metatavu/famifarm/reporting/xlsx/listreports/XlsxPlantingListReport.java
and got the absolute value for sapling duration.
> Fixed wrong date field in harvest report 

- src/main/java/fi/metatavu/famifarm/reporting/xlsx/AbstractXlsxBuilder.java
- src/main/java/fi/metatavu/famifarm/reporting/xlsx/listreports/XlsxPackingListReport.java
- src/test/java/fi/metatavu/famifarm/test/functional/AbstractFunctionalTest.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/ProductTestBuilderResource.java
- src/test/java/fi/metatavu/famifarm/test/functional/reporttests/ListReportTestsIT.java
https://github.com/Metatavu/famifarm-api/issues/322
> verification weightings as separate columns, null checks

- src/main/java/fi/metatavu/famifarm/filmbatches/PackagingFilmBatchController.java
- src/main/java/fi/metatavu/famifarm/packings/PackingController.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/PackagingFilmBatchDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/dao/PackingDAO.java
- src/main/java/fi/metatavu/famifarm/persistence/model/PackagingFilmBatch.java
- src/main/java/fi/metatavu/famifarm/persistence/model/Packing.java
- src/main/java/fi/metatavu/famifarm/rest/V1RESTService.java
- src/main/java/fi/metatavu/famifarm/rest/translate/PackagingFilmBatchTranslator.java
- src/main/java/fi/metatavu/famifarm/rest/translate/PackingTranslator.java
- src/main/resources/fi/metatavu/famifarm/server/liquibase/changelog.xml
- src/test/java/fi/metatavu/famifarm/test/functional/AbstractFunctionalTest.java
- src/test/java/fi/metatavu/famifarm/test/functional/PackagingFilmBatchTestIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/PackingTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/auth/AbstractTestBuilderAuthentication.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/PackagingFilmBatchTestResource.java
- src/test/java/fi/metatavu/famifarm/test/functional/builder/impl/PackingTestBuilderResource.java
- src/test/java/fi/metatavu/famifarm/test/functional/reporttests/ListReportTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/reporttests/SummaryReportTestsIT.java
- src/test/java/fi/metatavu/famifarm/test/functional/reporttests/WorkHoursReportTestsIT.java
https://github.com/Metatavu/famifarm-api/issues/327
> Add PackagingFilmBatch entity and related functionality
